version: '2'

services:
  webapp:
    env_file: .env
    build: ./webapp
    command: bash -c "rm /app/tmp/pids/server.pid; bundle exec rails s webrick -p 3000 -b '0.0.0.0'"
    volumes:
      - ./webapp:/app
    ports:
      - "3000:3000"
    depends_on:
      - devdb
  devdb:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
