version: '2'

services:
  web:
    env_file: .env
    build:
      context: ./webapp/.
      dockerfile: Dockerfile
    command: bash -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./webapp:/app
    ports:
      - "3000:3000"
  crawler:
    env_file: .env
    build:
      context: ./webapp/.
      dockerfile: Dockerfile.cron
    volumes:
      - ./webapp:/lib/tasks
    depends_on:
      - web
