version: '3'

services:
  webapp:
    build: ./webapp
    command: bash -c "rm /app/tmp/pids/server.pid; bundle exec rails s webrick -p 3000 -b '0.0.0.0'"
    user: "${SUDO_UID:-1000}"
    volumes:
      - ./webapp:/app
    network_mode: "host"
    depends_on:
      - devdb
    environment:
      RAILS_ENV: "development"

  devdb:
    build: ./database
    network_mode: "host"
    environment:
      POSTGRES_USER: "isamuni"
      POSTGRES_PASSWORD: "isamuni"