version: '2'

services:

  webapp:
    env_file: .env
    build: ./webapp
    command: bash -c "rm /app/tmp/pids/server.pid && bundle exec rails s webrick -p 3000 -b '0.0.0.0'"
    volumes:
      - ./webapp:/app
    ports:
      - "3000:3000" #only bind the rails app to localhost, so it is only reachable through nginx



