version: '2'

services:
  web:
    env_file: .env
    build: ./webapp
    command: bash -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./webapp:/app
    ports:
      - "3000:3000"
  crawler:
    env_file: .env
    build: ./webapp
    volumes:
      - ./webapp:/app
    command: clockwork crawler_clock.rb
