version: '2'

services:
  webapp:
    build: ./webapp
    command: bash -c "rm /app/tmp/pids/server.pid; bundle exec rails s webrick -p 3000 -b '0.0.0.0'"
    user: "1000"
    volumes:
      - ./webapp:/app
    ports:
      - "3000:3000"
      - "8080:8080"
    depends_on:
      - devdb
    env_file: .env
  devdb:
    build: ./database
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
