name: isamuni
root: ./

# tmux_command: byobu

windows:
  - server:
      layout: even-vertical
      panes:
        - rm ./tmp/pids/server.pid; bundle exec rails s webrick -b "0.0.0.0"
        - npm run dev -- --host="0.0.0.0"
  - shell:
      layout: main-vertical
      panes:
        - bash
        - bash
