FROM isamuni_web

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        cron

ADD crontab /etc/cron.d/crawl-cron
RUN chmod 0644 /etc/cron.d/crawl-cron
RUN touch /var/log/cron.log

CMD cron && tail -f /var/log/cron.log
