FROM ruby:2.3

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        postgresql-client \
        sqlite3 \
        cron \ 
        nodejs \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY Gemfile* ./
RUN bundle install

ADD crontab /etc/cron.d/crawl-cron
RUN chmod 0644 /etc/cron.d/crawl-cron
RUN touch /var/log/cron.log
RUN crontab /etc/cron.d/crawl-cron

CMD cron && tail -f /var/log/cron.log
